# Generated by Django 2.1.5 on 2019-01-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='contennt1',
        ),
    ]
