# Generated by Django 2.1.5 on 2019-01-26 23:43

from django.db import migrations, models
import tweets.validator


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190125_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweets.validator.validate_content]),
        ),
    ]
